# Generated by Django 5.1.3 on 2024-12-04 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_availableslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Confirmed')], default=1)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('consultation_notes', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(default='', limit_choices_to={'role': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_as_doctor', to='myapp.login')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.availableslot')),
                ('user', models.ForeignKey(default='', limit_choices_to={'role': 'User'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_as_user', to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(max_length=25)),
                ('insurance_provider', models.CharField(max_length=25)),
                ('coverage', models.CharField(max_length=25)),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('validity_start', models.DateField()),
                ('validity_end', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired')], default='Active', max_length=10)),
                ('user', models.ForeignKey(default='', limit_choices_to={'role': 'User'}, on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_detail', models.CharField(max_length=80)),
                ('dosage_instructions', models.TextField()),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('doctor', models.ForeignKey(default='', limit_choices_to={'role': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_as_doctor', to='myapp.login')),
                ('user', models.ForeignKey(default='', limit_choices_to={'role': 'User'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_as_user', to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateField(auto_now_add=True)),
                ('treatment_fees', models.IntegerField()),
                ('suggestion', models.TextField()),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(default='', limit_choices_to={'role': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='treatments_as_doctor', to='myapp.login')),
                ('user', models.ForeignKey(default='', limit_choices_to={'role': 'User'}, on_delete=django.db.models.deletion.CASCADE, related_name='treatments_as_user', to='myapp.login')),
            ],
        ),
    ]
