# Generated by Django 5.1.3 on 2024-12-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_appointment_insurance_prescription_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='insurance_doc',
            field=models.FileField(blank=True, default=None, null=True, upload_to='id_proofs/'),
        ),
    ]
